# version: '3.8'

services:
  backend:
    image: kthom20/simple-fortune-cookie:backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - frontend

  frontend:
    image: kthom20/simple-fortune-cookie:frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
