apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: kthom20/simple-fortune-cookie:backend
        ports:
        - containerPort: 9000
        envFrom:
            - configMapRef:
                name: backend-config