apiVersion: v1
kind: Service
metadata:
  name: backend-serivce
  labels:
    app: backend-service
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
