apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: kthom20/simple-fortune-cookie:frontend
        ports:
        - containerPort: 8080
        env:
          - name: BACKEND_PORT
            value: "9000"
          - name: BACKEND_DNS
            value: "backend-service"