name: Production workflow
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
    docker_username: kthom20
    docker_password: ${{secrets.DOCKER_PWD}}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4       
      - name: Build frontend
        run: bash CI/build-frontend.sh
      - name: Build backend
        run: bash CI/build-backend.sh
      - name: Test
        run: bash CI/test-app.sh
      - name: Upload repo
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .

  Docker-image:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      packages: write
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: build docker
        run: bash CI/docker-build.sh
      - name: push docker
        run: bash CI/docker-push.sh

  Test-docker:
    runs-on: ubuntu-latest
    needs: [Docker-image]
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Start docker
        run: docker compose -f docker-compose.yml up -d
      - name: Test docker
        run: bash CI/docker-test.sh
      - name: Stop docker
        run: docker compose down
    
  Deploy release:
    runs-on: ubuntu-latest
    needs: [Test-docker]
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Add kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig
      - name: Run kube deployment
        run: kubectl --kubeconfig=kubeconfig apply -f ./kubernetes --namespace=${{ env.ENVIRONMENT }}
